spring:
  application:
    name: demo
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=UTF-8&useSSL=true
    username: root
    password: 123456
    type: org.apache.tomcat.jdbc.pool.DataSource
server:
  context-path: /${spring.application.name}
  port: 9091