spring:
  application:
    name: demo
  profiles:
    active: dev

  #连接池配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=UTF-8&useSSL=true
    username: root
    password: 123456
    type: org.apache.tomcat.jdbc.pool.DataSource
  second-datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=UTF-8&useSSL=true
    username: root
    password: 123456
    type: org.apache.tomcat.jdbc.pool.DataSource
    #数据源配置
    dynamic:
      maxWaitMillis: 10000
      initialSize: 5
      maxTotal: 8
      maxIdle: 5
      minIdle: 2
      validationQuery: SELECT *
      primary:
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/test
        username: root
        password: 123456
        connectionProperties: useUnicode=true&characterEncoding=UTF-8&useSSL=true
      slave:
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/test
        username: root
        password: 123456
server:
  context-path: /${spring.application.name}
  port: 9094
mybatis:
  type-aliases-package:
  mapper-locations:
