spring:
  application:
    name: demo
  profiles:
    active: dev

  #连接池配置
  datasource:
    dynamic:
      master:
        #使用tomcat内置数据源
#        driver-class-name: com.mysql.jdbc.Driver
#        url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf-88&useSSL=true
#        username: root
#        password: 123456
#        type: org.apache.tomcat.jdbc.pool.DataSource

        #使用dbcp2数据源
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false
        username: root
        password: 123456
        maxWaitMillis: 10000
        initialSize: 5
        maxTotal: 8
        maxIdle: 5
        minIdle: 2
        validationQuery: SELECT 1
      slave:
#        driver-class-name: com.mysql.jdbc.Driver
#        url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=true
#        username: root
#        password: 123456
#        type: org.apache.tomcat.jdbc.pool.DataSource

        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false
        username: root
        password: 123456
        maxWaitMillis: 10000
        initialSize: 5
        maxTotal: 8
        maxIdle: 5
        minIdle: 2
        validationQuery: SELECT 1
server:
  context-path: /${spring.application.name}
  port: 9094